#!/bin/sh
# @see http://thinca.hatenablog.com/entry/20150306/1425639218
while read local_ref local_sha1 remote_ref remote_sha1
do
  if [ "${remote_ref##refs/heads/}" = "master" ]; then
    echo "Can't push to master branch."
    exit 1
  fi
done
